name: Build FastAPI Docker Image

on:
  push:
    branches:
      - main

jobs:
  download_model:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies for model training
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run model training script
      run: python model_training.py
      working-directory: ./  # Assuming the script is at the root of the repository

    - name: Cache trained model (optional)
      uses: actions/cache@v3
      with:
        path: ./model
        key: ${{ runner.os }}-model-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-model-

  build_and_deploy:
    needs: download_model
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t duyluann/fastapi-app .

    - name: Push Docker image
      run: |
        docker push duyluann/fastapi-app
